inherits:
  - duplicated
  - utils:base
  - utils:fix
  - utils:no-design-checks

mypy:
  options:
    python-version: '3.9'

bandit:
  disable:
    - B404 # Consider possible security implications associated with the subprocess module.

ruff:
  options:
    target-version: py39
