inherits:
  - duplicated
  - utils:base
  - utils:fix
  - utils:no-design-checks

ignore-paths:
  - add-pre-commit-hooks
  - collect
  - create-empty-recomit-config
  - create-version
  - fix-precommit-files
  - gmf-saas
  - open-git-config-file
  - open-github-settings
  - remove-merged-branches
  - update-ubuntu-verion-in-ci
  - upgrade-c2cciutils-to-1.6
  - upgrade-c2cciutils-to-1.7
  - upgrade-ci-2024
  - upgrade-python
  - use-ghcr
  - use-prospector-profile
  - use-renovate-to-trigger-rebuild
  - versions-tree

mypy:
  run: False

bandit:
  disable:
    - B404 # Consider possible security implications associated with the subprocess module.

ruff:
  options:
    target-version: py39
