#!/usr/bin/env python3

import os

import multi_repo_automation as mra
import ruamel.yaml.comments

# if os.path.exists(".github/renovate.json5"):
# if mra.run(["grep", "text", ".github/renovate.json5"], exit_on_error=False).returncode != 0: # not found
# if mra.git_grep(r"\<text\>"]): # found
# if mra.run(["git", "ls-files", "**/*.txt"], stdout=subprocess.PIPE).stdout.strip() != b"": # found
# mra.edit("file")
# input()


def fix_files(pre_commit_config, files: str) -> str:
    add_start_end = False
    if files.strip().startswith("(?x)"):
        files = files.strip()[4:]
    if files.strip().startswith("(") and files.strip().endswith(")"):
        files_list = files.strip()[1:-1].split("|")
    elif files.strip().startswith("(") and files.strip().endswith(")"):
        files_list = files.strip()[1:-1].split("|")
    elif files.strip().startswith("^(") and files.strip().endswith(")$"):
        files_list = files.strip()[2:-2].split("|")
        add_start_end = True
    else:
        return files

    return pre_commit_config.create_files_regex([f.strip() for f in files_list], add_start_end=add_start_end)


def _do() -> None:
    if os.path.exists(".pre-commit-config.yaml"):
        with mra.EditPreCommitConfig() as pre_commit_config:
            for repo in pre_commit_config.data["repos"]:
                for hook in repo["hooks"]:
                    if len(hook.get("files", "")) > 60:
                        hook["files"] = fix_files(pre_commit_config, hook["files"])
                    if len(hook.get("exclude", "")) > 60:
                        hook["exclude"] = fix_files(pre_commit_config, hook["exclude"])


if __name__ == "__main__":
    mra.main(
        _do,
        # pull_request_on_stabilization_branches
        # pull_request_title
        # pull_request_body
        # branch
        # pull_request_branch_prefix
        config={
            "branch": "fix-repo",
            "pull_request_title": "Fix the files in the pre-commit config",
            "pull_request_body": "This is done by the automated script named fix-repo",
        },
    )
