#!/usr/bin/env python3


import os
import subprocess

import c2cciutils.security
import multi_repo_automation as mra
import requests
import ruamel
import toml
import yaml
from identify import identify
from ruamel.yaml import YAML

# if os.path.exists(".github/renovate.json5"):
# if mra.run(["grep", "text", ".github/renovate.json5"], exit_on_error=False).returncode != 0: # not found
# if mra.git_grep(r"\<text\>"]): # found
# if mra.run(["git", "ls-files", "**/*.txt"], stdout=subprocess.PIPE).stdout.strip() != b"": # found
# mra.edit("file")
# input()


def _do() -> None:
    if os.path.exists("pyproject.toml"):
        try:
            subprocess.run(["poetry", "--version"], check=True)
        except Exception:
            with mra.EditTOML("pyproject.toml") as pyproject:
                poetry = pyproject.setdefault("tool", {}).setdefault("poetry", {})
                poetry.setdefault("name", os.path.basename(os.getcwd()))
                poetry.setdefault("version", "0.0.0")
                poetry.setdefault("description", "TODO: Add a description")
                # poetry.setdefault('authors', ["Stéphane Brunner <stephane.brunner@gmail.com>"])
                poetry.setdefault("authors", ["Camptocamp <info@camptocamp.com>"])

            # description = "AngularJS OpenLayers Library"
            # description = "Demo of GeoMapFish Application"
            mra.edit(["pyproject.toml"])


if __name__ == "__main__":
    mra.main(
        _do,
        # pull_request_on_stabilization_branches
        # pull_request_title
        # pull_request_body
        # branch
        # pull_request_branch_prefix
        # config={},
        config={
            "branch": "pyproject-config-fix",
            "pull_request_branch_prefix": "pyproject-config-fix-",
            "pull_request_title": "Add missing configuration in pyproject.toml",
            "pull_request_body": "Needed to make `poetry --version` work, used in the audit.",
        },
        description="Update the repository for c2cciutils version 1.6, the will also fix the errors he found",
    )
