#!/usr/bin/env python3

import subprocess

import c2cciutils.security
import multi_repo_automation as mra
import requests
import ruamel
import toml
import yaml
from identify import identify
from ruamel.yaml import YAML

# if os.path.exists(".github/renovate.json5"):
# if mra.run(["grep", "text", ".github/renovate.json5"], exit_on_error=False).returncode != 0: # not found
# if mra.git_grep(r"\<text\>"]): # found
# if mra.run(["git", "ls-files", "**/*.txt"], stdout=subprocess.PIPE).stdout.strip() != b"": # found
# mra.edit("file")
# input()


def _do() -> None:
    for workflow_file in mra.run(
        ["git", "ls-files", ".github/workflows/*.yaml"], stdout=subprocess.PIPE
    ).stdout.split("\n"):
        if workflow_file:
            with mra.EditYAML(workflow_file) as yaml:
                for job in yaml["jobs"].values():
                    if job.get("runs-on", "").startswith("ubuntu-"):
                        if job["runs-on"] == "ubuntu-20.04":
                            job["runs-on"] = "ubuntu-22.04"


if __name__ == "__main__":
    mra.main(
        _do,
        # pull_request_on_stabilization_branches
        # pull_request_title
        # pull_request_body
        # branch
        # pull_request_branch_prefix
        config={
            "pull_request_on_stabilization_branches": True,
            "pull_request_branch_prefix": "update-ubuntu",
            "pull_request_title": "Update the used Ubuntu version to from 20.04 to 22.04 in the workflows",
            "pull_request_body": "",
        },
    )
